language: python
python:
- 3.7.8
- 3.8
- 3.9
group: dev
install:
- pip install -r tests/requirements.txt
- pip install .
env:
- PYTHONPATH=.
script:
- python -Werror tests/smoke_test.py
- python -m unittest discover tests
- echo test
